### ISSUE TITLE
lol?

### ISSUE THREAD

**Issue by Gloryness** [Joseph0M/Tassomai-Answer-Lookup#1]
well im actually flattered you included me in the README i thought you didn't so fair enough

this github repo will probably get DMCA'd though

**Comment by Joseph0M** [comment]
After your Repo had been DMCA'd, I was inspired to create my own, as i quite like using my limited skillset to bypass and cheat the system. The repo originally had the JSON file attached, but it was later DMCA'd so i removed it and provided instructions on how to get it from me. I tried a different approach from you, rather than using their APIs that could quite easily break, I just used their json database (although this wasn't easy, questions where formatted weirdly, and I was struggling to convert LaTeX equations both ways to be read correctly)
